#!/bin/sh

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'
